version: '2'
services:
  postgres:
    container_name: postgres-omxs
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=dai
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    expose:
      - "5432"
      - "9113"
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      postgres:

  pgadmin:
    container_name: pgadmin-omxs
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=ken.dai@outlook.com
      - PGADMIN_DEFAULT_PASSWORD=dai
    ports:
      - "5050:80"
    networks:
      postgres:

networks:
    postgres:
    
